spring:
  datasource:
    url: ${TEST_NOTIFICATION_DB_URL}
    username: ${TEST_NOTIFICATION_DB_USERNAME}
    password: ${TEST_NOTIFICATION_DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: NOTIFICATION-SERVICE

server:
  port: 8086

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${TEST_EUREKA_SERVER_URL}
