server:
  port: 8070

eureka:
  instance:
    hostname: ${EUREKA_TEST_HOSTNAME}
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/